In [15]:
!pip install randomuser
!pip install pandas

Requirement already satisfied: randomuser in /Users/alokjp/Desktop/API_Learning_Route-1/.venv/lib/python3.13/site-packages (1.6)
Requirement already satisfied: pandas in /Users/alokjp/Desktop/API_Learning_Route-1/.venv/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /Users/alokjp/Desktop/API_Learning_Route-1/.venv/lib/python3.13/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/alokjp/Desktop/API_Learning_Route-1/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/alokjp/Desktop/API_Learning_Route-1/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [16]:
from randomuser import RandomUser
import pandas as pd

In [17]:
r = RandomUser()

In [18]:
some_list = r.generate_users(10)

In [19]:
some_list

[<randomuser.RandomUser at 0x113bd0950>,
 <randomuser.RandomUser at 0x113bd0890>,
 <randomuser.RandomUser at 0x113bd0fb0>,
 <randomuser.RandomUser at 0x113bd1010>,
 <randomuser.RandomUser at 0x113bd1070>,
 <randomuser.RandomUser at 0x113bd10d0>,
 <randomuser.RandomUser at 0x113bd1130>,
 <randomuser.RandomUser at 0x113bd1190>,
 <randomuser.RandomUser at 0x113bd11f0>,
 <randomuser.RandomUser at 0x113bd1250>]

In [20]:
name = r.get_full_name()

In [21]:
for user in some_list:
    print(user.get_full_name()," ",user.get_email())

Nooa Maunu   nooa.maunu@example.com
Niklas Lakso   niklas.lakso@example.com
Sofia Taylor   sofia.taylor@example.com
Fiona Ferreira   fiona.ferreira@example.com
Bryan Dupuis   bryan.dupuis@example.com
Linda Day   linda.day@example.com
Danielle Flores   danielle.flores@example.com
Enrique Gomez   enrique.gomez@example.com
Ethan Da Silva   ethan.dasilva@example.com
Mounia Gierveld   mounia.gierveld@example.com

In [22]:
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/men/54.jpg
https://randomuser.me/api/portraits/men/68.jpg
https://randomuser.me/api/portraits/women/80.jpg
https://randomuser.me/api/portraits/women/69.jpg
https://randomuser.me/api/portraits/men/7.jpg
https://randomuser.me/api/portraits/women/50.jpg
https://randomuser.me/api/portraits/women/50.jpg
https://randomuser.me/api/portraits/men/64.jpg
https://randomuser.me/api/portraits/men/89.jpg
https://randomuser.me/api/portraits/women/19.jpg

In [23]:
#function to generate dataframe 
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [24]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Dale Fletcher,male,Skerries,Dún Laoghaire–Rathdown,dale.fletcher@example.com,1951-02-18T01:33:44.539Z,https://randomuser.me/api/portraits/men/4.jpg
1,Zita Nicolas,female,Tschugg,Schwyz,zita.nicolas@example.com,1979-10-18T13:44:59.446Z,https://randomuser.me/api/portraits/women/44.jpg
2,Tormod Rognmo,male,Algarheim,Telemark,tormod.rognmo@example.com,1973-12-09T14:14:22.214Z,https://randomuser.me/api/portraits/men/15.jpg
3,Amanda Lassila,female,Kiiminki,Central Ostrobothnia,amanda.lassila@example.com,1964-08-24T00:56:14.358Z,https://randomuser.me/api/portraits/women/73.jpg
4,Alexandra Englund,female,Vear,Vest-Agder,alexandra.englund@example.com,1990-02-12T04:51:32.549Z,https://randomuser.me/api/portraits/women/65.jpg
5,Kuzey Çamdalı,male,Kütahya,Bartın,kuzey.camdali@example.com,1984-06-06T22:09:43.492Z,https://randomuser.me/api/portraits/men/79.jpg
6,Lisiane Ferreira,female,Viamão,Ceará,lisiane.ferreira@example.com,1968-09-12T21:04:44.840Z,https://randomuser.me/api/portraits/women/22.jpg
7,Ceyhan Özkök,female,Kayseri,İzmir,ceyhan.ozkok@example.com,1996-11-30T17:11:06.636Z,https://randomuser.me/api/portraits/women/56.jpg
8,Kim Parker,female,Roscommon,Leitrim,kim.parker@example.com,1988-04-12T05:58:21.842Z,https://randomuser.me/api/portraits/women/3.jpg
9,Laurie Knight,female,Fountainbleu,Nunavut,laurie.knight@example.com,1957-11-26T05:01:24.903Z,https://randomuser.me/api/portraits/women/96.jpg

In [25]:
df1 = pd.DataFrame(get_users())
df1

,Name,Gender,City,State,Email,DOB,Picture
0,Emily Ferguson,female,Laytown-Bettystown-Mornington,Kerry,emily.ferguson@example.com,1993-12-20T16:56:20.823Z,https://randomuser.me/api/portraits/women/76.jpg
1,محمد کریمی,male,آمل,کردستان,mhmd.khrymy@example.com,1947-04-22T04:49:45.504Z,https://randomuser.me/api/portraits/men/64.jpg
2,Roberto Martinez,male,San Sebastián,Ceuta,roberto.martinez@example.com,1965-12-20T19:00:29.951Z,https://randomuser.me/api/portraits/men/16.jpg
3,Gonçalo Barbier,male,Buchs (Zh),Solothurn,goncalo.barbier@example.com,1963-05-25T22:38:57.965Z,https://randomuser.me/api/portraits/men/25.jpg
4,Daryl Sullivan,male,Perth,Western Australia,daryl.sullivan@example.com,1959-07-24T15:17:10.826Z,https://randomuser.me/api/portraits/men/60.jpg
5,Benito Castro,male,Orense,Melilla,benito.castro@example.com,1987-07-13T11:16:35.823Z,https://randomuser.me/api/portraits/men/30.jpg
6,Maeva Ennis,female,Carleton,Québec,maeva.ennis@example.com,1946-06-11T16:17:37.150Z,https://randomuser.me/api/portraits/women/55.jpg
7,Frederik Mortensen,male,Oure,Hovedstaden,frederik.mortensen@example.com,1979-04-19T01:56:07.580Z,https://randomuser.me/api/portraits/men/2.jpg
8,Lester Hansen,male,Ballarat,New South Wales,lester.hansen@example.com,1965-04-21T08:44:15.047Z,https://randomuser.me/api/portraits/men/58.jpg
9,Isla Halla,female,Vesilahti,Uusimaa,isla.halla@example.com,1966-09-08T04:06:50.461Z,https://randomuser.me/api/portraits/women/47.jpg